---
version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supergeheim
      MYSQL_USER: admin
      MYSQL_PASSWORD: supergeheim
      MYSQL_DATABASE: drupal

  drupal_app:
    build: .
    depends_on: 
      - db
    ports:
      - "80:80"
    volumes:
      - ./sites:/var/www/html/sites
      - ./themes:/var/www/html/themes
    environment:
      MYSQL_ROOT_PASSWORD: supergeheim
      MYSQL_USER: admin
      MYSQL_PASSWORD: supergeheim
      MYSQL_DATABASE: drupal
      MYSQL_HOST: db
      LDAP_PASSWD: supergeheim
